### ISSUE TITLE
Invalid Key Length Error

### ISSUE THREAD

**Issue by Tanay-Bharadwaj** [CodeWithHarry/myshop-strapi-ecommerce#1]
This is my custom.js code as follows:

const { createCoreController } = require('@strapi/strapi').factories;
const https = require('https');
const PaytmChecksum = require('paytmchecksum');

module.exports = createCoreController('api::order.order', ({ strapi }) => ({
    // Method 1: Creating an entirely custom action
    async exampleAction(ctx) {

        /*
        * import checksum generation utility
        * You can get this utility from https://developer.paytm.com/docs/checksum/
        */

        var paytmParams = {};

        paytmParams.body = {
            "requestType": "Payment",
            "mid": process.env.MID,
            "websiteName": "YOUR_WEBSITE_NAME",
            "orderId": "ORDERID_98765",
            "callbackUrl": "https://localhost:1337/api/orders/posttransacion",
            "txnAmount": {
                "value": "1.00",
                "currency": "INR",
            },
            "userInfo": {
                "custId": "CUST_001",
            },
        };

        /*
        * Generate checksum by parameters we have in body
        * Find your Merchant Key in your Paytm Dashboard at https://dashboard.paytm.com/next/apikeys 
        */
       let checksum = await PaytmChecksum.generateSignature(JSON.stringify(paytmParams.body), process.env.MKEY)
        paytmParams.head = {
            "signature": checksum
        };
        var post_data = JSON.stringify(paytmParams);

        const gettoken = async () => {
            return new Promise((resolve, reject) => {

                var options = {

                    /* for Staging */
                    //hostname: 'securegw-stage.paytm.in',

                    /* for Production */
                    // hostname: 'securegw.paytm.in',

                    port: 443,
                    path: '/theia/api/v1/initiateTransaction?mid=${process.env.MID}&orderId=ORDERID_98765',
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Content-Length': post_data.length
                    }
                };

                var response = "";
                var post_req = https.request(options, function (post_res) {
                    post_res.on('data', function (chunk) {
                        response += chunk;
                    });

                    post_res.on('end', function () {
                        console.log('Response: ', response);
                        resolve.response
                    });
                });

                post_req.write(post_data);
                post_req.end();

            })

        }

        let myr = await gettoken()
        ctx.body = myr;

    },

}));
 I have not written the complete code because i am stuck at an error.

error: Invalid key length
RangeError: Invalid key length
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Function.encrypt (/Users/tanay/myshop/node_modules/paytmchecksum/PaytmChecksum.js:11:23)
    at Function.calculateChecksum (/Users/tanay/myshop/node_modules/paytmchecksum/PaytmChecksum.js:93:24)
    at Function.generateSignatureByString (/Users/tanay/myshop/node_modules/paytmchecksum/PaytmChecksum.js:55:24)
    at async Object.exampleAction (/Users/tanay/myshop/src/api/order/controllers/custom.js:40:23)
    at async returnBodyMiddleware (/Users/tanay/myshop/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/tanay/myshop/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async serve (/Users/tanay/myshop/node_modules/koa-static/index.js:59:5)
    at async returnBodyMiddleware (/Users/tanay/myshop/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/tanay/myshop/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /Users/tanay/myshop/node_modules/@strapi/strapi/lib/middlewares/body.js:25:7
    at async /Users/tanay/myshop/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /Users/tanay/myshop/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5

And my PatymChecksum.js file is as follows which lies in my node_modules folder.

"use strict";

var crypto = require('crypto');

class PaytmChecksum {

	static encrypt(input, key) {
		
		
		var cipher = crypto.createCipheriv('AES-128-CBC', key, PaytmChecksum.iv);
		var encrypted = cipher.update(input, 'binary', 'base64');
		encrypted += cipher.final('base64');
		return encrypted;
	}
	static decrypt(encrypted, key) {
		var decipher = crypto.createDecipheriv('AES-128-CBC', key, PaytmChecksum.iv);
		var decrypted = decipher.update(encrypted, 'base64', 'binary');
		try {
			decrypted += decipher.final('binary');
		}
		catch (e) {
			console.log(e);
		}
		return decrypted;
	}
	static generateSignature(params, key) {
		if (typeof params !== "object" && typeof params !== "string") {
			var error = "string or object expected, " + (typeof params) + " given.";
			return Promise.reject(error);
		}
		if (typeof params !== "string"){
			params = PaytmChecksum.getStringByParams(params);
		}
		return PaytmChecksum.generateSignatureByString(params, key);
	}
	

	static verifySignature(params, key, checksum) {
		if (typeof params !== "object" && typeof params !== "string") {
		   	var error = "string or object expected, " + (typeof params) + " given.";
			return Promise.reject(error);
		}
		if(params.hasOwnProperty("CHECKSUMHASH")){
			delete params.CHECKSUMHASH
		}
		if (typeof params !== "string"){
			params = PaytmChecksum.getStringByParams(params);
		}
		return PaytmChecksum.verifySignatureByString(params, key, checksum);
	}

	static async generateSignatureByString(params, key) {
		var salt = await PaytmChecksum.generateRandomString(4);
		return PaytmChecksum.calculateChecksum(params, key, salt);
	}

	static verifySignatureByString(params, key, checksum) {		
		var paytm_hash = PaytmChecksum.decrypt(checksum, key);
		var salt = paytm_hash.substr(paytm_hash.length - 4);
		return (paytm_hash === PaytmChecksum.calculateHash(params, salt));
	}

	static generateRandomString(length) {
		return new Promise(function (resolve, reject) {
			crypto.randomBytes((length * 3.0) / 4.0, function (err, buf) {
				if (!err) {
					var salt = buf.toString("base64");
					resolve(salt);					
				}
				else {
					console.log("error occurred in generateRandomString: " + err);
					reject(err);
				}
			});
		});
	}

	static getStringByParams(params) {
		var data = {};
		Object.keys(params).sort().forEach(function(key,value) {
			data[key] = (params[key] !== null && params[key].toLowerCase() !== "null") ? params[key] : "";
		});
		return Object.values(data).join('|');
	}

	static calculateHash(params, salt) {		
		var finalString = params + "|" + salt;
		return crypto.createHash('sha256').update(finalString).digest('hex') + salt;
	}
	static calculateChecksum(params, key, salt) {		
		var hashString = PaytmChecksum.calculateHash(params, salt);
		return PaytmChecksum.encrypt(hashString,key);
	}
}
PaytmChecksum.iv = '@@@@&&&&####$$$$';
module.exports = PaytmChecksum;

So can you figure out where I am wrong?If yes paste a refreshed correct code for me.

Node Version of mine is 6.
Strapi is V4.

Please reply @CodeWithHarry as soon as possible.

**Comment by Tanay-Bharadwaj** [comment]
@CodeWithHarry please reply on the issue.

**Comment by Tanay-Bharadwaj** [comment]
@CodeWithHarry  i am stuck in this from many days.please help
